//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceNetworks
    {
        public int Number { get; set; }
        public int networkID { get; set; }
        public int deviceID { get; set; }
    
        public virtual Devices Devices { get; set; }
        public virtual Networks Networks { get; set; }
    }
}
