//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NetworkBaseEntities : DbContext
    {
        public NetworkBaseEntities()
            : base("name=NetworkBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<idDevice> idDevices { get; set; }
        public virtual DbSet<userInfo> userInfoes { get; set; }
        public virtual DbSet<baseUser> baseUsers { get; set; }
        public virtual DbSet<network> networks { get; set; }
    }
}
