//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class network
    {
        public int deviceID { get; set; }
        public string networkName { get; set; }
    
        public virtual idDevice idDevice { get; set; }
    }
}
